name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "BREAKING CHANGES:"
    label: breaking
  - title: "FEATURES:"
    label: enhancement
  - title: "IMPROVEMENTS:"
    label:
      - 'improvement'
      - 'change'
  - title: "BUG FIXES:"
    label: bug
  - title: "OTHER:"
    label:
      - 'chore'
      - 'refactor'
      - 'documentation'
version-resolver:
  major:
    labels:
      - 'first'
      - 'new_version'
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'improvement'
      - 'change'
      - 'bug'
      - 'chore'
      - 'refactor'
      - 'documentation'
      - 'renovate'
  default: patch
change-template: "- $TITLE (#$NUMBER)"
template: |
  $CHANGES
