version: '3'
services:
  bulder:
    build:
      context: .
      args:
        host_uid: $CUID
        host_gid: $CGID
        user: $CU
    tty: true
    volumes:
      - ../:/go/src/terraform-provider-mysql
      - ~/.terraform.d/plugins:/home/$USER/.terraform.d/plugins
      - ~/go/pkg:/go/pkg
    working_dir: /go/src/terraform-provider-mysql
    environment:
      GO111MODULE: on
